### ISSUE TITLE
Add info copy to top of JDKs page

### ISSUE THREAD

**Issue by marc0der** [sdkman/sdkman.github.io#24]
I would like the following copy added to the top of the JDKs page. Perhaps styled differently from the vendor blocks so that it stands out more:

**Why is Temurin the default JDK?**

_We’ve chosen Eclipse Temurin as our default JDK because it’s widely recognized as the de facto standard for OpenJDK distributions. Trusted for its reliability, stability, and performance, Temurin is ideal for production-grade development. We ensure our default version aligns with the latest stable release, so you’re equipped with the best tools for your JVM projects._

_Looking ahead, we plan to give you the flexibility to track the latest JDK releases from individual vendors, such as Oracle or Amazon Corretto. While this isn’t available yet, we’re working to make it easier for you to stay on top of the specific distributions you rely on._

**Comment by SvMak** [comment]
@marc0der Could you check this to see if the result suits you?

![Screenshot 2024-10-29 160833](https://github.com/user-attachments/assets/c4435483-83dd-4989-8192-8e8727aaee27)

**Comment by SvMak** [comment]
Done. PR #25
